/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
  @Test fun `Santa moves R3,L2 is 5 blocks`() {
    val expectedBlocks = 5
    val actualBlocks = howFarDidSantaGo("R3,L2")
    assertEquals(expectedBlocks, actualBlocks)
  }

  @Test fun `Santa move R2,R2,R2 is 2 blocks`() {
    val expectedBlocks = 2
    val actualBlocks = howFarDidSantaGo("R2,R2,R2")
    assertEquals(expectedBlocks, actualBlocks)
  }

  @Test fun `Santa move R2,R2,R2,R2 is 0 blocks`() {
    val expectedBlocks = 0
    val actualBlocks = howFarDidSantaGo("R2,R2,R2,R2")
    assertEquals(expectedBlocks, actualBlocks)
  }

  @Test fun `Santa move R5, L5, R5, R3 is 12 blocks`() {
    val expectedBlocks = 12
    val actualBlocks = howFarDidSantaGo("R5, L5, R5, R3")
    assertEquals(expectedBlocks, actualBlocks)
  }

  @Test fun `Santa move "L4, R2, R4, L5, L3, L1, R4, R5" is 18 blocks`() {
    val expectedBlocks = 18
    val actualBlocks = howFarDidSantaGo("L4, R2, R4, L5, L3, L1, R4, R5")
    assertEquals(expectedBlocks, actualBlocks)
  }

  @Test fun `Santa moves R20, R30 is 50 blocks`() {
    val expectedBlocks = 50
    val actualBlocks = howFarDidSantaGo("R20, R30")
    assertEquals(expectedBlocks, actualBlocks)
  }

  @Test fun `Santa moving R8, R4, R4, R8 hits the same spot 4 blocks away (Due east)`() {
    val expectedBlocks = 4
    val actualBlocks = whereWasSantaWhenHeHitTheSamePlace("R8, R4, R4, R8")
    assertEquals(expectedBlocks, actualBlocks)
  }
}
