/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File

fun howFarDidSantaGo(input: String): Int {
  var direction: Direction = North(Point(0, 0))

  for (step in input.split(',')) {
    val stripped = step.trim()
    val dir = stripped[0]
    val distance = stripped.substring(1).toInt()

    direction = direction.move(dir, distance)
  }

  return direction.point.distance()
}

fun whereWasSantaWhenHeHitTheSamePlace(input: String): Int {
  val inputs = input.split(',')
  var visited = ArrayList<Line>(inputs.size)

  var direction: Direction = North(Point(0, 0))
  var previousLine: Line? = null
  for (step in inputs) {
    val stripped = step.trim()
    val dir = stripped[0]
    val distance = stripped.substring(1).toInt()

    val newDirection = direction.move(dir, distance)
    val newLine = Line(direction.point, newDirection.point)
    direction = newDirection

    for (line in visited) {
      val overlap = newLine.overlaps(line)
      if (overlap != null) {
        return overlap.distance()
      }
    }

    // Make sure we wait until the following round to add the previous line
    if (previousLine != null) {
      visited.add(previousLine)
    }
    previousLine = newLine
  }

  return -1
}

fun main(args: Array<String>) {
  val fileContent = File(args[0]).readText()
  println(howFarDidSantaGo(fileContent))
  println(whereWasSantaWhenHeHitTheSamePlace(fileContent))
}
